### ISSUE TITLE
Missing STL for SB-front_MOS-PLUS

### ISSUE THREAD

**Issue by eduncan911** [BondtechAB/Voron#1]
First! j/k

~~For the **LGX Lite for Voron CW2 Stealthburner**, the STEP file is missing the non-CPAP Front cover (I think they should be called "frontcover" instead of "front", as there are two fronts for the PLUS.~~ As mentioned in comments, use the original front cover.

See 1st comment below.

![image](https://user-images.githubusercontent.com/104980/214729704-e95b6aca-451a-4182-a216-95ddc3260f39.png)

**Comment by eduncan911** [comment]
And... It looks like the STLs for both the SB-front_MOS-PLUS, ~~and the reported missing object in OP, are both missing from the STL directory:~~

https://github.com/BondtechAB/Voron/tree/main/Voron_2.4-VT-SW/LGX_lite/STL/SB%20_MOS

**Comment by ogland** [comment]
Hi! Mosquito uses the same cover as standard SB. The SB front is found at the credits: [https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/bythorsthunder/Stealthburner_Rapido_Uhf](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/bythorsthunder/Stealthburner_Rapido_Uhf)

I'll make this more clear in the readme.

**Comment by eduncan911** [comment]
Ok, great.  That covers (phun) the non-PLUS.

Now, that just leaves the STL export of the PLUS front cover that is missing from the Repo, as originally reported in the 2nd comment above.

**Comment by eduncan911** [comment]
Updated the Title, and 2nd post for what's remaining.

Also, could you re-open until the STL posted?

**Comment by ogland** [comment]
The STL won't be uploaded. It's available in the repo linked to in the readme.
