### ISSUE TITLE
[Talk] Design Considerations

### ISSUE THREAD

**Issue by eduncan911** [BondtechAB/Voron#2]
Thank you for posting this design.  I've been tinkering with LGX Lite designs, trying to make something work with my custom VolcoMosq setup (which uses the Mosquito's Radiator/Heatsink and mount).  This design gets close, however, there's still significant work.  I'll see what I can do about merging the two designs (maybe a PR).

I would like to ask about the design considerations in this project for certain features.

## 1. **Hotend Fan Ducting - Fully encapsulating the Mosquito's Radiator/Heatsink**

This is unusual; but, very cool!  The duct-work of how the air is shaped and then compressed down into shape of the heatsink, forces all air over the heatbreak where nothing escapes over the sides.  Very clever.

I am inquiring about how well this has been tested, and to what temps.  My concern is that the heatsink itself was designed for free-air cooling from a low-speed fan, with airflow over the entire heatsink.  But encapsulating the entire heatsink, to where even the sides are not exposed, is new.

## 2. **Heater-block Melting?**

The Mosquito's and Magnum (non-plus) are notorious for melting cooling ducts and x-carriages due to its large, wide design and cooling ducts that want to reach around the heatsink.

When I placed a Mosquito in the CAD, it shows that the heater-block is partially encapsulated/very close to the top of the block for the rear mounts.

How well has this been tested, and at what temps for what periods of time?  Unless the "Front/Rear" and X-Carriage parts are all printed in PC6+CF, I can't see how this won't melt - and very quickly.

**Comment by ogland** [comment]
Hi! The solution works quite well with a full encapsulating silicone sock. I'm working with Slice to see what the best solution is. But for now I think I will add the moulds for DIYers to make their own. Thanks for your input!

**Comment by eduncan911** [comment]
What were the printing temps, and how many hours does that printer have on it?

Could you give details?  "Works quite well" is not very specific to the details asked.

**Comment by ogland** [comment]
I have printed at 270C hotend temp and 110 bed temp for a couple of days, with the longest print so far being 5 hours. No deformation.  
  
The standard fan for the mosquito doesn't blow on the outside edges of the heatsink. It's a 25 mm fan bolted directly to the 25 mm wide heatsink, so I assumed this would work as good on this setup. Of course we need volume to be sure, and that's why it's posted here for the public to use and report back :)

**Comment by jurikaur** [comment]
Whitch way was it meant to mount on SB? Heater and thermistor back or front?

**Comment by eduncan911** [comment]
No idea.  I'd say whichever keeps it away from the plastic.  :)

sorry i didn't close this out before.
